"""The default skin must render exactly what the app rendered before skins.

`ui/skin.py` was an EXTRACTION, not a redesign: every value in `DEFAULT` was
read out of the old `ui/theme.py` and `ui/widgets.py`. That claim is only
worth anything if it is checked, because a wrong digit in a colour map is
invisible in review and produces a subtly different app.

`tests/scene_hashes.txt` was generated by rendering all 118 scenes at the
commit BEFORE skins existed (aa335b9) and hashing their draw calls. The
comparison passed byte-for-byte at extraction time; this test keeps it that
way.

WHEN A HASH LEGITIMATELY CHANGES
--------------------------------
Only when the default look is deliberately changed. Regenerate with:

    python3 -m pytest tests/test_skin_identity.py --regenerate-hashes

and say in the commit message what moved and why. A regeneration with no
visual intent behind it is how a look drifts.
"""
import hashlib
import os

import pytest

from tests.scenes import SCENES

HASHES = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                      "scene_hashes.txt")


def scene_hash(name):
    hw, _ = SCENES[name]()
    return hashlib.sha256(repr(hw.display.calls).encode()).hexdigest()[:16]


def _recorded():
    with open(HASHES) as f:
        return dict(line.split() for line in f if line.strip())


def pytest_addoption(parser):  # pragma: no cover - opt-in maintenance path
    parser.addoption("--regenerate-hashes", action="store_true")


def test_every_scene_is_recorded():
    """A new screen must join the baseline, or it is unguarded."""
    recorded = _recorded()
    missing = sorted(set(SCENES) - set(recorded))
    assert not missing, (
        "scenes with no recorded hash (add them to tests/scene_hashes.txt): %r"
        % missing)


def test_no_stale_records():
    recorded = _recorded()
    gone = sorted(set(recorded) - set(SCENES))
    assert not gone, "recorded hashes for scenes that no longer exist: %r" % gone


@pytest.mark.parametrize("name", sorted(SCENES))
def test_default_skin_renders_identically(name):
    recorded = _recorded()
    assert scene_hash(name) == recorded[name], (
        "%s renders differently under the default skin. If that is intended, "
        "regenerate tests/scene_hashes.txt and say why in the commit." % name)


def test_default_skin_is_the_registered_default():
    """The control must stay the control.

    A direction that quietly edits DEFAULT instead of deriving from it would
    move the baseline out from under every comparison.
    """
    from ui.skin import DEFAULT, DEFAULT_COLORS, DEFAULT_CHROME

    assert DEFAULT.name == "default"
    assert DEFAULT.colors == DEFAULT_COLORS
    assert DEFAULT.chrome == DEFAULT_CHROME
